fix: force http1 when invoking other runtime actions
adobe/helix-content-proxy pull request #235
Opened 2020-12-04 15:24 UTC by stefan-guggisberg

The upcoming/new I/O Runtime environment is Azure-based and supports HTTP/2. This might lead to issues with long-lived HTTP/2 sessions.

fix #196

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues
#196 

Thanks for contributing!

2020-12-04 20:16 UTC, trieloff approved these changes

2020-12-05 04:56 UTC, tripodsan requested changes
don't remove `if`

2020-12-05 04:56 UTC, tripodsan commented on src/utils.js
> -  if (process.env.HELIX_FETCH_FORCE_HTTP1) {
I would keep the `if` and just set `process.env.HELIX_FETCH_FORCE_HTTP1 = 'true'`

2020-12-06 01:11 UTC, tripodsan approved these changes

2020-12-06 14:31 UTC, merged

2020-12-06 14:35 UTC, trieloff commented
:tada: This PR is included in version 2.3.3 :tada:

The release is available on:
- `v2.3.3`
- [GitHub release](https://github.com/adobe/helix-content-proxy/releases/tag/v2.3.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: